### ISSUE TITLE
Can't get test app working on Android 12 or 14

### ISSUE THREAD

**Issue by jpage4500** [MuntashirAkon/libadb-android#10]
I tried running this app on both a Galaxy S10 (Android 12) and Pixel 7 (Android 14) and neither of them work.

Nothing happens when I enter a command and hitting the connect icon just show a toast message "Disconnected from ADB!" (I don't think it was ever connected)

I can dig deeper but wanted to see what devices or OS versions this app should work on or has been tested on?

```
03-01 11:19:20.664	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 5555) from /:: (port 43868): connect failed: ECONNREFUSED (Connection refused)	
03-01 11:19:20.664	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at libcore.io.IoBridge.connect(IoBridge.java:188)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at java.net.Socket.connect(Socket.java:621)	

03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at java.net.Socket.connect(Socket.java:570)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at java.net.Socket.<init>(Socket.java:450)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at java.net.Socket.<init>(Socket.java:218)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at io.github.muntashirakon.adb.AdbConnection.<init>(AdbConnection.java:194)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	... 10 more	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at libcore.io.Linux.connect(Native Method)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at libcore.io.ForwardingOs.connect(ForwardingOs.java:204)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:157)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at libcore.io.ForwardingOs.connect(ForwardingOs.java:204)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at libcore.io.IoBridge.connectErrno(IoBridge.java:202)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	at libcore.io.IoBridge.connect(IoBridge.java:180)	
03-01 11:19:20.665	io.github.muntashirakon.adb.testapp	9634	9740	W	System.err	 	... 20 more	

```

**Comment by MuntashirAkon** [comment]
> I can dig deeper but wanted to see what devices or OS versions this app should work on or has been tested on?

Tested on Android 11 (physical device), Android 5 and 12 (emulator). All works well. You need to ensure that ADB is working in port 5555. Test app is for demonstration purpose only, not for general use, since it's not exactly user-friendly.

**Comment by MuntashirAkon** [comment]
Tested on Android 14. Working fine. Make sure it's paired correctly and/or ADB over TCP is working at port 5555.
